version: 2
jobs:
  build trial:
    docker:
      - image: dlanguage/dmd:2.079.0
    steps:
      - run: apt-get update
      - run: apt-get install -y libevent-dev libssl-dev
      - run: git clone https://github.com/gedaiu/trial.git
      - run: cd trial && dub build :runner
      - persist_to_workspace:
          root: .
          paths:
            - trial

  ldc-1.2:
    docker:
      - image: dlanguage/ldc:1.2.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: trial/trial
      - run: dub --root=test/unit-threaded
      - run: dub --root=test/disabledSourceResult
      - run: dub --root=test/disabledMessageResult
      - run: dub --root=test/disabledDiffResult

workflows:
  version: 2
  tests:
    jobs:
      - build
      - test examples:
          requires:
            - build
      - vibe test:
          requires:
            - build